-- Migration 001: Initial Schema
-- Create initial database schema with users, posts, and comments

-- =============================================================================
-- USERS TABLE
-- =============================================================================

CREATE TABLE IF NOT EXISTS users (
  id text PRIMARY KEY,
  email text UNIQUE NOT NULL,
  name text NOT NULL,
  role text NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'moderator', 'admin')),
  credits integer NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- Enable RLS
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

-- Users can read their own profile
CREATE POLICY read_own_profile ON users
FOR SELECT
TO authenticated
USING (auth.user_id() = id);

-- Users can update their own profile (but not role or credits)
CREATE POLICY update_own_profile ON users
FOR UPDATE
TO authenticated
USING (auth.user_id() = id);

-- Admins can see all users
CREATE POLICY admin_read_all_users ON users
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM users WHERE id = auth.user_id() AND role = 'admin'
  )
);

-- =============================================================================
-- POSTS TABLE
-- =============================================================================

CREATE TABLE IF NOT EXISTS posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title text NOT NULL,
  content text NOT NULL,
  is_published boolean DEFAULT false,
  published_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- Indexes for performance
CREATE INDEX idx_posts_user_id ON posts(user_id);
CREATE INDEX idx_posts_published ON posts(is_published, published_at DESC) WHERE is_published = true;
CREATE INDEX idx_posts_created_at ON posts(created_at DESC);

-- Enable RLS
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;

-- Anyone can read published posts
CREATE POLICY read_published_posts ON posts
FOR SELECT
TO authenticated
USING (is_published = true);

-- Users can manage their own posts
CREATE POLICY manage_own_posts ON posts
FOR ALL
TO authenticated
USING (auth.user_id() = user_id)
WITH CHECK (auth.user_id() = user_id);

-- Moderators and admins can see all posts
CREATE POLICY moderators_read_all_posts ON posts
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM users 
    WHERE id = auth.user_id() 
    AND role IN ('moderator', 'admin')
  )
);

-- =============================================================================
-- COMMENTS TABLE
-- =============================================================================

CREATE TABLE IF NOT EXISTS comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id bigint NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  content text NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- Indexes
CREATE INDEX idx_comments_post_id ON comments(post_id, created_at);
CREATE INDEX idx_comments_user_id ON comments(user_id);

-- Enable RLS
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;

-- Users can see comments on published posts
CREATE POLICY read_comments_on_published_posts ON comments
FOR SELECT
TO authenticated
USING (
  post_id IN (SELECT id FROM posts WHERE is_published = true)
);

-- Users can see comments on their own posts
CREATE POLICY read_comments_on_own_posts ON comments
FOR SELECT
TO authenticated
USING (
  post_id IN (SELECT id FROM posts WHERE user_id = auth.user_id())
);

-- Users can create comments on published posts
CREATE POLICY create_comments ON comments
FOR INSERT
TO authenticated
WITH CHECK (
  auth.user_id() = user_id AND
  post_id IN (SELECT id FROM posts WHERE is_published = true)
);

-- Users can update their own comments
CREATE POLICY update_own_comments ON comments
FOR UPDATE
TO authenticated
USING (auth.user_id() = user_id);

-- Users can delete their own comments
CREATE POLICY delete_own_comments ON comments
FOR DELETE
TO authenticated
USING (auth.user_id() = user_id);

-- =============================================================================
-- FUNCTIONS
-- =============================================================================

-- Update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers for updated_at
CREATE TRIGGER update_users_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_posts_updated_at
  BEFORE UPDATE ON posts
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_comments_updated_at
  BEFORE UPDATE ON comments
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Set published_at when post is published
CREATE OR REPLACE FUNCTION set_published_at()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.is_published = true AND OLD.is_published = false THEN
    NEW.published_at = now();
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_posts_published_at
  BEFORE UPDATE ON posts
  FOR EACH ROW
  EXECUTE FUNCTION set_published_at();

-- =============================================================================
-- GRANT PERMISSIONS (for Data API)
-- =============================================================================

-- Grant usage on schema
GRANT USAGE ON SCHEMA public TO authenticated;

-- Grant table permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO authenticated;

-- Grant sequence permissions (for IDENTITY columns)
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- Grant for future tables
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO authenticated;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO authenticated;
