-- Migration 002: Add Tags System
-- Add tags and post_tags tables for content categorization

-- =============================================================================
-- TAGS TABLE
-- =============================================================================

CREATE TABLE IF NOT EXISTS tags (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL,
  slug text UNIQUE NOT NULL,
  description text,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- Index for lookups
CREATE INDEX idx_tags_slug ON tags(slug);

-- Enable RLS
ALTER TABLE tags ENABLE ROW LEVEL SECURITY;

-- Everyone can read tags
CREATE POLICY read_all_tags ON tags
FOR SELECT
TO authenticated
USING (true);

-- Only admins can create/update/delete tags
CREATE POLICY admin_manage_tags ON tags
FOR ALL
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM users WHERE id = auth.user_id() AND role = 'admin'
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM users WHERE id = auth.user_id() AND role = 'admin'
  )
);

-- =============================================================================
-- POST_TAGS TABLE (Many-to-Many)
-- =============================================================================

CREATE TABLE IF NOT EXISTS post_tags (
  post_id bigint NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  tag_id bigint NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now() NOT NULL,
  PRIMARY KEY (post_id, tag_id)
);

-- Indexes
CREATE INDEX idx_post_tags_post_id ON post_tags(post_id);
CREATE INDEX idx_post_tags_tag_id ON post_tags(tag_id);

-- Enable RLS
ALTER TABLE post_tags ENABLE ROW LEVEL SECURITY;

-- Users can see tags on published posts
CREATE POLICY read_tags_on_published_posts ON post_tags
FOR SELECT
TO authenticated
USING (
  post_id IN (SELECT id FROM posts WHERE is_published = true)
);

-- Users can see tags on their own posts
CREATE POLICY read_tags_on_own_posts ON post_tags
FOR SELECT
TO authenticated
USING (
  post_id IN (SELECT id FROM posts WHERE user_id = auth.user_id())
);

-- Users can add tags to their own posts
CREATE POLICY add_tags_to_own_posts ON post_tags
FOR INSERT
TO authenticated
WITH CHECK (
  post_id IN (SELECT id FROM posts WHERE user_id = auth.user_id())
);

-- Users can remove tags from their own posts
CREATE POLICY remove_tags_from_own_posts ON post_tags
FOR DELETE
TO authenticated
USING (
  post_id IN (SELECT id FROM posts WHERE user_id = auth.user_id())
);

-- =============================================================================
-- HELPER FUNCTIONS
-- =============================================================================

-- Function to get or create a tag by slug
CREATE OR REPLACE FUNCTION get_or_create_tag(tag_name text, tag_slug text)
RETURNS bigint AS $$
DECLARE
  tag_id bigint;
BEGIN
  -- Try to get existing tag
  SELECT id INTO tag_id FROM tags WHERE slug = tag_slug;
  
  -- Create if doesn't exist
  IF tag_id IS NULL THEN
    INSERT INTO tags (name, slug) VALUES (tag_name, tag_slug) RETURNING id INTO tag_id;
  END IF;
  
  RETURN tag_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to add tags to a post
CREATE OR REPLACE FUNCTION add_tags_to_post(p_post_id bigint, p_tag_ids bigint[])
RETURNS void AS $$
DECLARE
  tag_id bigint;
BEGIN
  FOREACH tag_id IN ARRAY p_tag_ids
  LOOP
    INSERT INTO post_tags (post_id, tag_id)
    VALUES (p_post_id, tag_id)
    ON CONFLICT (post_id, tag_id) DO NOTHING;
  END LOOP;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =============================================================================
-- VIEWS FOR CONVENIENCE
-- =============================================================================

-- View: Posts with their tags
CREATE OR REPLACE VIEW posts_with_tags AS
SELECT 
  p.*,
  COALESCE(
    json_agg(
      json_build_object(
        'id', t.id,
        'name', t.name,
        'slug', t.slug
      )
    ) FILTER (WHERE t.id IS NOT NULL),
    '[]'::json
  ) as tags
FROM posts p
LEFT JOIN post_tags pt ON pt.post_id = p.id
LEFT JOIN tags t ON t.id = pt.tag_id
GROUP BY p.id;

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON tags TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON post_tags TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
