-- Migration 003: Add Analytics Tracking
-- Add views, likes, and analytics tables

-- =============================================================================
-- POST VIEWS TABLE
-- =============================================================================

CREATE TABLE IF NOT EXISTS post_views (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id bigint NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  user_id text REFERENCES users(id) ON DELETE SET NULL,
  ip_address inet,
  user_agent text,
  viewed_at timestamptz DEFAULT now() NOT NULL
);

-- Indexes for analytics queries
CREATE INDEX idx_post_views_post_id ON post_views(post_id, viewed_at DESC);
CREATE INDEX idx_post_views_user_id ON post_views(user_id) WHERE user_id IS NOT NULL;
CREATE INDEX idx_post_views_viewed_at ON post_views(viewed_at);

-- Enable RLS
ALTER TABLE post_views ENABLE ROW LEVEL SECURITY;

-- Post owners can see views on their posts
CREATE POLICY post_owners_see_views ON post_views
FOR SELECT
TO authenticated
USING (
  post_id IN (SELECT id FROM posts WHERE user_id = auth.user_id())
);

-- Anyone can record a view
CREATE POLICY anyone_can_view ON post_views
FOR INSERT
TO authenticated
WITH CHECK (true);

-- =============================================================================
-- POST LIKES TABLE
-- =============================================================================

CREATE TABLE IF NOT EXISTS post_likes (
  post_id bigint NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now() NOT NULL,
  PRIMARY KEY (post_id, user_id)
);

-- Indexes
CREATE INDEX idx_post_likes_post_id ON post_likes(post_id);
CREATE INDEX idx_post_likes_user_id ON post_likes(user_id);

-- Enable RLS
ALTER TABLE post_likes ENABLE ROW LEVEL SECURITY;

-- Users can see likes on published posts
CREATE POLICY see_likes_on_published_posts ON post_likes
FOR SELECT
TO authenticated
USING (
  post_id IN (SELECT id FROM posts WHERE is_published = true)
);

-- Users can like published posts
CREATE POLICY like_published_posts ON post_likes
FOR INSERT
TO authenticated
WITH CHECK (
  auth.user_id() = user_id AND
  post_id IN (SELECT id FROM posts WHERE is_published = true)
);

-- Users can unlike posts
CREATE POLICY unlike_posts ON post_likes
FOR DELETE
TO authenticated
USING (auth.user_id() = user_id);

-- =============================================================================
-- ANALYTICS MATERIALIZED VIEW
-- =============================================================================

-- Create materialized view for post statistics
CREATE MATERIALIZED VIEW post_statistics AS
SELECT 
  p.id as post_id,
  p.user_id,
  p.title,
  p.is_published,
  p.created_at,
  COUNT(DISTINCT pv.id) as view_count,
  COUNT(DISTINCT pl.user_id) as like_count,
  COUNT(DISTINCT c.id) as comment_count,
  COUNT(DISTINCT pv.id) FILTER (WHERE pv.viewed_at > now() - interval '7 days') as views_last_7_days,
  COUNT(DISTINCT pl.user_id) FILTER (WHERE pl.created_at > now() - interval '7 days') as likes_last_7_days
FROM posts p
LEFT JOIN post_views pv ON pv.post_id = p.id
LEFT JOIN post_likes pl ON pl.post_id = p.id
LEFT JOIN comments c ON c.post_id = p.id
WHERE p.is_published = true
GROUP BY p.id, p.user_id, p.title, p.is_published, p.created_at;

-- Indexes on materialized view
CREATE INDEX idx_post_stats_post_id ON post_statistics(post_id);
CREATE INDEX idx_post_stats_user_id ON post_statistics(user_id);
CREATE INDEX idx_post_stats_views ON post_statistics(view_count DESC);
CREATE INDEX idx_post_stats_likes ON post_statistics(like_count DESC);

-- Function to refresh statistics
CREATE OR REPLACE FUNCTION refresh_post_statistics()
RETURNS void AS $$
BEGIN
  REFRESH MATERIALIZED VIEW CONCURRENTLY post_statistics;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =============================================================================
-- ANALYTICS FUNCTIONS
-- =============================================================================

-- Get trending posts (most views in last 7 days)
CREATE OR REPLACE FUNCTION get_trending_posts(limit_count integer DEFAULT 10)
RETURNS TABLE (
  post_id bigint,
  title text,
  view_count bigint,
  like_count bigint,
  trend_score numeric
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    ps.post_id,
    ps.title,
    ps.view_count,
    ps.like_count,
    (ps.views_last_7_days * 1.0 + ps.likes_last_7_days * 2.0) as trend_score
  FROM post_statistics ps
  ORDER BY trend_score DESC
  LIMIT limit_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Get user post statistics
CREATE OR REPLACE FUNCTION get_user_stats(p_user_id text)
RETURNS TABLE (
  total_posts bigint,
  total_views bigint,
  total_likes bigint,
  total_comments bigint,
  avg_views_per_post numeric,
  avg_likes_per_post numeric
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    COUNT(*)::bigint as total_posts,
    COALESCE(SUM(ps.view_count), 0)::bigint as total_views,
    COALESCE(SUM(ps.like_count), 0)::bigint as total_likes,
    COALESCE(SUM(ps.comment_count), 0)::bigint as total_comments,
    COALESCE(AVG(ps.view_count), 0) as avg_views_per_post,
    COALESCE(AVG(ps.like_count), 0) as avg_likes_per_post
  FROM post_statistics ps
  WHERE ps.user_id = p_user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Record a post view (with deduplication)
CREATE OR REPLACE FUNCTION record_post_view(
  p_post_id bigint,
  p_user_id text DEFAULT NULL,
  p_ip_address inet DEFAULT NULL,
  p_user_agent text DEFAULT NULL
)
RETURNS void AS $$
DECLARE
  existing_view_id bigint;
BEGIN
  -- Check if user viewed this post in last hour (deduplication)
  IF p_user_id IS NOT NULL THEN
    SELECT id INTO existing_view_id
    FROM post_views
    WHERE post_id = p_post_id
      AND user_id = p_user_id
      AND viewed_at > now() - interval '1 hour'
    LIMIT 1;
    
    IF existing_view_id IS NOT NULL THEN
      -- Already counted this view recently
      RETURN;
    END IF;
  END IF;
  
  -- Record the view
  INSERT INTO post_views (post_id, user_id, ip_address, user_agent)
  VALUES (p_post_id, p_user_id, p_ip_address, p_user_agent);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =============================================================================
-- SCHEDULED JOB (via pg_cron if available)
-- =============================================================================

-- Note: pg_cron needs to be installed and configured
-- This is just an example of how to schedule refreshes

-- Refresh statistics every hour
-- SELECT cron.schedule('refresh-post-stats', '0 * * * *', 'SELECT refresh_post_statistics()');

-- =============================================================================
-- GRANTS
-- =============================================================================

GRANT SELECT, INSERT ON post_views TO authenticated;
GRANT SELECT, INSERT, DELETE ON post_likes TO authenticated;
GRANT SELECT ON post_statistics TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
