#!/usr/bin/env python3
"""
API Client for Google Calendar API
Auto-generated by Skill Builder
"""
import os
import requests
import time

class Google Calendar ApiClient:
    """Client for Google Calendar API API"""
    
    def __init__(self, api_key=None):
        self.api_key = api_key or os.environ.get('GOOGLE CALENDAR API_API_KEY')
        if not self.api_key:
            raise ValueError(f"{'GOOGLE CALENDAR API_API_KEY'} environment variable required")
        
        self.base_url = "https://api.Google Calendar API.com"  # TODO: Update base URL
        self.session = requests.Session()
        self.session.headers.update({
            'Authorization': f'Bearer {self.api_key}',
            'Content-Type': 'application/json'
        })
    
    def _request(self, method, endpoint, **kwargs):
        """Make HTTP request with error handling and retry"""
        url = f"{self.base_url}{endpoint}"
        max_retries = 3
        
        for attempt in range(max_retries):
            try:
                response = self.session.request(method, url, **kwargs)
                response.raise_for_status()
                return response.json()
            except requests.exceptions.HTTPError as e:
                if e.response.status_code == 429:  # Rate limit
                    wait_time = 2 ** attempt
                    print(f"⚠️  Rate limited. Waiting {wait_time}s...")
                    time.sleep(wait_time)
                    continue
                raise
            except requests.exceptions.RequestException as e:
                if attempt == max_retries - 1:
                    raise
                time.sleep(1)
        
        raise Exception("Max retries exceeded")
    
    def get(self, endpoint, **kwargs):
        """GET request"""
        return self._request('GET', endpoint, **kwargs)
    
    def post(self, endpoint, data=None, **kwargs):
        """POST request"""
        return self._request('POST', endpoint, json=data, **kwargs)
    
    # TODO: Add specific API methods here
    
    def test_connection(self):
        """Test API connection"""
        try:
            # TODO: Replace with actual test endpoint
            result = self.get('/test')
            print("✅ API connection successful")
            return True
        except Exception as e:
            print(f"❌ API connection failed: {str(e)}")
            return False

# Example usage
if __name__ == '__main__':
    client = Google Calendar ApiClient()
    client.test_connection()
